### ISSUE TITLE
More detailed README

### ISSUE THREAD

**Issue by bdhhtb** [pbbarnes/BarnesCS294Project#1]
Add a description of what your code will do, who it's for, and maybe some example commands

**Comment by bdhhtb** [comment]
Also mention any dependencies -- I tried to run it and got this message:

```
Traceback (most recent call last):
  File "Demo.py", line 3, in <module>
    import DEMO1
  File "/Users/brian/Code/STUDENT_PROJECTS/REPOS/paul.xml_and_stuff/DEMO1.py", line 11, in <module>
    from openpyxl.styles.colors import BLUE
ImportError: cannot import name BLUE
```
